Django_project/store-server/store/orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView, OrderDetailView, OrdersHistoryView,
                          SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('create', OrderCreateView.as_view(), name='create'),
    path('', OrdersHistoryView.as_view(), name='history'),
    path('success', SuccessTemplateView.as_view(), name='success'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order')
]

Django_project/store-server/store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('user/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_project/store-server/store/orders/models.py
from random import choice

from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    class Status(models.IntegerChoices):
        CREATED = 0, 'Создан'
        PAID = 1, 'Оплачен'
        ON_THE_WAY = 2, 'В пути'
        DELIVERED = 3, 'Доставлено'

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    delivery_address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    user_created_order = models.ForeignKey(to=User, on_delete=models.CASCADE)
    status = models.PositiveIntegerField(choices=Status.choices, default=Status.CREATED)

    def __str__(self):
        return f'Order #{self.id} - {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.user_created_order)
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum())
        }
        baskets.delete()

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.update_after_payment()
        self.status = 1 if choice([True, False]) else 0
        return super(Order, self).save()

Django_project/store-server/store/orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Иван'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Иванов'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'you@example.com'
    }))
    delivery_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Россия, Москва, ул. Мира, дом 6'
    }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'delivery_address')

Django_project/store-server/store/orders/views.py
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order


class OrderCreateView(TitleMixin, CreateView):
    form_class = OrderForm
    model = Order
    template_name = 'orders/order-create.html'
    title = 'Store - Оформление заказа'
    success_url = reverse_lazy('orders:success')

    def form_valid(self, form):
        form.instance.user_created_order = self.request.user
        return super(OrderCreateView, self).form_valid(form)


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/order-success.html'
    title = 'Store - Спасибо за заказ!'


class OrdersHistoryView(TitleMixin, ListView):
    model = Order
    title = 'Store - Заказы'
    template_name = 'orders/orders.html'
    ordering = '-created'

    def get_queryset(self):
        queryset = super(OrdersHistoryView, self).get_queryset()
        return queryset.filter(user_created_order=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - Заказ #{self.object.id}'
        return context

Django_project/store-server/store/orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}


{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ basket.product.name }}</h6>
                            <small class="text-muted">{{ basket.quantity }} шт.</small>
                        </div>
                        <span class="text-muted">{{ basket.sum|intcomma }} руб.</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ baskets.total_sum|intcomma }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.delivery_addressy.id_for_label }}" class="form-label">Адрес</label>
                            {{ form.delivery_address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Django_project/store-server/store/orders/templates/orders/order-success.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4> Ваш заказ успешно сформирован.</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'products:index' %}">Вернуться в каталог</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

Django_project/store-server/store/orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}


{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказ №{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Кол-во</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Сумма</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product_item in object.basket_history.purchased_items %}
                        <tr>
                            <th scope="row">
                                {{ product_item.product_name }}
                            </th>
                            <td>{{ product_item.quantity }}</td>
                            <td>{{ product_item.price|intcomma }} руб.</td>
                            <td>{{ product_item.sum|intcomma }} руб.</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum|intcomma }} руб.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Django_project/store-server/store/orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'vendor/css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                        <tr class="{% if order.status %} table-success {% else %} table-info {% endif %}">
                            <th scope="row">{{ order.id }}</th>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.created|naturaltime }}</td>
                            <td>{{ order.basket_history.total_sum|intcomma }} руб.</td>
                            <td>
                                <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}}